FROM openjdk:8
ADD target/backend-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c'echo spring.datasource.url=jdbc:mysql://mysql:3306/conygre > application.properties'
RUN sh -c 'echo spring.datasource.username=root >> application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre >> application.properties'
ENV JAVA_OPS=""
ENTRYPOINT [ "sh', "-c", "java $JAVA_OPTS - Djava.security.egd=file:/dev./urandom -jar /app.jat" ]

